POST  http://localhost:3001/api/v1/auth/register
Content-Type: application/json

{
    "nama" : "Nanang Setiawan",
    "email" : "yurinahirate@gmail.com",
    "password" : "secretpassword"
}

###
POST http://localhost:3001/api/v1/mainBudget
Content-Type: application/json

{
    "userId" : "90694f99-133d-4693-bcb3-7d18648b80d3"
}

###
GET http://localhost:3001/api/v1/mainBudget/eee24def-db65-4949-a9aa-a69478b9f59c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE4ODUyNTN9.RZ_9Q2dPRhWIcYQwygXpuVl8ERUdpSl9pXibIFYr6OA

# Hapus Main Budget
###
DELETE http://localhost:3001/api/v1/mainBudget/37d22c49-66b7-4567-a560-00d7c15ab2d4

###
POST  http://localhost:3001/api/v1/auth/regis



#INCOME ROUTE

#Buat income
###
POST http://localhost:3001/api/v1/income/budget/63d1eca4-7585-451d-877a-240eaa09ca29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE5OTAxMTB9.XSMRJRNmmxJanPr6qJchPhzrxvmICVlO4KkyQ_QxF9c
Content-Type: application/json

{
    "title" : "Gaji",
    "budget" : 6000000
}

#Delete Income
###
DELETE http://localhost:3001/api/v1/income/budget/63d1eca4-7585-451d-877a-240eaa09ca29/7b0afa61-5577-4edb-8b4a-f5866ccd19b4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE5OTAxMTB9.XSMRJRNmmxJanPr6qJchPhzrxvmICVlO4KkyQ_QxF9c

#Update Income
###
PUT http://localhost:3001/api/v1/income/budget/63d1eca4-7585-451d-877a-240eaa09ca29/e5a7f7de-98ba-4925-b811-ab4727d99683
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE5OTAxMTB9.XSMRJRNmmxJanPr6qJchPhzrxvmICVlO4KkyQ_QxF9c
Content-Type: application/json

{
    "title" : "Jual Hp",
    "budget" : 100000
}

#Lihat Income

###
GET http://localhost:3001/api/v1/income/budget/63d1eca4-7585-451d-877a-240eaa09ca29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE5OTAxMTB9.XSMRJRNmmxJanPr6qJchPhzrxvmICVlO4KkyQ_QxF9c



#EXPENSE API

###
GET http://localhost:3001/api/v1/expense-plan/

###
GET http://localhost:3001/api/v1/expense-plan/plan/2b2961a9-0a11-4149-bbbe-f9c9b0c73ff2


###
POST http://localhost:3001/api/v1/expense-plan/
Content-Type: application/json

{
    "idMainBudget" : "63d1eca4-7585-451d-877a-240eaa09ca29",
    "title" : "Beli Kuota",
    "maxExpense" : 100000
}

###
DELETE http://localhost:3001/api/v1/expense-plan/d31fab4f-3a21-4b9b-948c-3f1046e909a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE5OTAxMTB9.XSMRJRNmmxJanPr6qJchPhzrxvmICVlO4KkyQ_QxF9c

###
PUT http://localhost:3001/api/v1/expense-plan/d31fab4f-3a21-4b9b-948c-3f1046e909a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE5OTAxMTB9.XSMRJRNmmxJanPr6qJchPhzrxvmICVlO4KkyQ_QxF9c
Content-Type: application/json

{
    "idMainBudget" : "63d1eca4-7585-451d-877a-240eaa09ca29",
    "title" : "Beli Buah",
    "maxExpense" : 2000
}

###
GET http://localhost:3001/api/v1/expense-plan/63d1eca4-7585-451d-877a-240eaa09ca29


#EXPENSE ROUTE

###
POST http://localhost:3001/api/v1/expense
Content-Type: application/json

{
    "idExpensePlan" : "e4b64ef8-d9a0-4754-b569-4df650488af7",
    "title" : "erta",
    "budget" : 20000
}

###
DELETE http://localhost:3001/api/v1/expense/e09a28dd-0697-463e-aee0-a772b78e3c80


###
PUT http://localhost:3001/api/v1/expense/408c7295-e9ad-4e8d-95a8-f42d05e6b8d6
Content-Type: application/json

{
    "idExpensePlan" : "9cefe3d9-e803-4b3a-bfe0-0e6c71631075",
    "title" : "updated",
    "budget" : 10000
}

###
GET http://localhost:3001/api/v1/expense/9cefe3d9-e803-4b3a-bfe0-0e6c71631075



###
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "email" : "yurinahirate@gmail.com",
    "password" : "secretpassword"
}

###
GET http://localhost:3001/api/v1/mainBudget/eee24def-db65-4949-a9aa-a69478b9f59c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jcmVkZW50aWFsIjoiZmEwZjE3YTQtMzY5ZS00MWI5LWE3ZGEtODg5ODQ4M2I5NWUxIiwidXNlcklkIjoiZWVlMjRkZWYtZGI2NS00OTQ5LWE5YWEtYTY5NDc4YjlmNTljIiwidG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKamNtVmtaVzUwYVdGc1NXUWlPaUptWVRCbU1UZGhOQzB6TmpsbExUUXhZamt0WVRka1lTMDRPRGs0TkRnellqazFaVEVpTENKMWMyVnlTV1FpT2lKbFpXVXlOR1JsWmkxa1lqWTFMVFE1TkRrdFlUbGhZUzFoTmprME56aGlPV1kxT1dNaUxDSmxlSEFpT2pFMk56UTNNVFUzTkRsOS5YM2RaM3NQT1ZINDFfVnA0NmVZMnlqdkFmYXhNaHhWLW9tR2ZPTjgyTlU4IiwiZXhwIjoxNjcyMTI0MDI0fQ.3LN4zOxL0ukb5NMtdExjt5ODZWlwn907DXG3ecViIUY


###
GET http://localhost:3001/api/v1/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE5OTAxMTB9.XSMRJRNmmxJanPr6qJchPhzrxvmICVlO4KkyQ_QxF9c


# Helper DB
###
#POST  http://localhost:3001/api/v1/auth/empty

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzIxNjMyOTJ9.EkiG1fHWiy-ByiJUu3Xk8LtYhWjoeKRH4vHLLVxrcJo