POST  http://localhost:3001/api/v1/auth/register
Content-Type: application/json

{
    "nama" : "Nanang Setiawan",
    "email" : "yurinahirate@gmail.com",
    "password" : "secretpassword"
}

###
POST http://localhost:3001/api/v1/mainBudget
Content-Type: application/json

{
    "userId" : "90694f99-133d-4693-bcb3-7d18648b80d3"
}

###
GET http://localhost:3001/api/v1/mainBudget/eee24def-db65-4949-a9aa-a69478b9f59c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE4ODUyNTN9.RZ_9Q2dPRhWIcYQwygXpuVl8ERUdpSl9pXibIFYr6OA

# Hapus Main Budget
###
DELETE http://localhost:3001/api/v1/mainBudget/37d22c49-66b7-4567-a560-00d7c15ab2d4

###
POST  http://localhost:3001/api/v1/auth/regis



#INCOME ROUTE

#Buat income
###
POST http://localhost:3001/api/v1/income/budget/d059117b-4610-4bcc-8ad3-dd8edb1c3ca2
Content-Type: application/json

{
    "title" : "Gaji",
    "budget" : 6000000
}

#Delete Income
###
DELETE http://localhost:3001/api/v1/income/budget/9f220a50-a289-42bf-ab9c-11d51693d718/626fd750-690e-4d4d-9ccf-f3c631b97859

#Update Income
###
PUT http://localhost:3001/api/v1/income/budget/9f220a50-a289-42bf-ab9c-11d51693d718/626fd750-690e-4d4d-9ccf-f3c631b97859
Content-Type: application/json

{
    "title" : "Payah",
    "budget" : 600000
}

#Lihat Income

###
GET http://localhost:3001/api/v1/income/budget/9ff2804b-7821-487d-a5c9-95702f922a11



#EXPENSE API

###
GET http://localhost:3001/api/v1/expense-plan/

###
POST http://localhost:3001/api/v1/expense-plan/
Content-Type: application/json

{
    "idMainBudget" : "d059117b-4610-4bcc-8ad3-dd8edb1c3ca2",
    "title" : "Beli Kuota",
    "maxExpense" : 100000
}

###
DELETE http://localhost:3001/api/v1/expense-plan/305024e9-792f-4f3a-b9c6-fd1777be3daa


###
PUT http://localhost:3001/api/v1/expense-plan/305024e9-792f-4f3a-b9c6-fd1777be3daa
Content-Type: application/json

{
    "idMainBudget" : "d059117b-4610-4bcc-8ad3-dd8edb1c3ca2",
    "title" : "Beli Kuota",
    "maxExpense" : 100000
}

###
GET http://localhost:3001/api/v1/expense-plan/408c7295-e9ad-4e8d-95a8-f42d05e6b8d6


#EXPENSE ROUTE

###
POST http://localhost:3001/api/v1/expense
Content-Type: application/json

{
    "idExpensePlan" : "9cefe3d9-e803-4b3a-bfe0-0e6c71631075",
    "title" : "kedua",
    "budget" : 1000
}

###
DELETE http://localhost:3001/api/v1/expense/e09a28dd-0697-463e-aee0-a772b78e3c80


###
PUT http://localhost:3001/api/v1/expense/408c7295-e9ad-4e8d-95a8-f42d05e6b8d6
Content-Type: application/json

{
    "idExpensePlan" : "9cefe3d9-e803-4b3a-bfe0-0e6c71631075",
    "title" : "updated",
    "budget" : 10000
}

###
GET http://localhost:3001/api/v1/expense/9cefe3d9-e803-4b3a-bfe0-0e6c71631075



###
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "email" : "yurinahirate@gmail.com",
    "password" : "secretpassword"
}

###
GET http://localhost:3001/api/v1/mainBudget/eee24def-db65-4949-a9aa-a69478b9f59c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFsSWQiOiJmYTBmMTdhNC0zNjllLTQxYjktYTdkYS04ODk4NDgzYjk1ZTEiLCJ1c2VySWQiOiJlZWUyNGRlZi1kYjY1LTQ5NDktYTlhYS1hNjk0NzhiOWY1OWMiLCJleHAiOjE2NzE4ODUyNTN9.RZ_9Q2dPRhWIcYQwygXpuVl8ERUdpSl9pXibIFYr6OA


# Helper DB
###
#POST  http://localhost:3001/api/v1/auth/empty